### ISSUE TITLE
Enter key always selects date

### ISSUE THREAD

**Issue by andredewaard** [PixelBoii/vue-headless-datepicker#1]
On pressing enter while focussing on with the 'tab' key on next or prev month and pressing 'enter' it will still select the date that is highlighted. 

Great plugin btw. Any plans to keep supporting this?

**Comment by PixelBoii** [comment]
> Great plugin btw. Any plans to keep supporting this?

Thanks! Yeah, I plan to continue working on this and try to reach a stable release at some point, but no clear dates yet. Regardless, my aim is that it should be usable right now - The only drawback is that there may be breaking changes between patch versions.

I make use of this here, so the development on the two are sort of connected fwiw: https://github.com/PixelBoii/time-tracker

> On pressing enter while focussing on with the 'tab' key on next or prev month and pressing 'enter' it will still select the date that is highlighted.

I'll be sure to have a look into this 👍

**Comment by PixelBoii** [comment]
This should've been fixed in https://github.com/PixelBoii/vue-headless-datepicker/releases/tag/v0.0.14 so I'll go ahead and close this, but please let me know if you still have issues with this.
